version: 2

general:
  branches:
    only:
      - master # list of branches to build

jobs:
  build:
    working_directory: /home/launchpad

    docker:
      - image: docker:latest

    steps:
      - setup_remote_docker
      - checkout

      # install OS dependencies
      - run: apk update && apk upgrade && apk add --no-cache bash git openssh sshpass

      # deploy the build (if on a deployment branch)
      - add_ssh_keys:
          fingerprints:
              - "31:7b:75:15:9a:1d:09:2c:5d:7f:82:2c:38:0f:2e:d7"
      - deploy:
          name: Docker Image Deploment
          command: .circleci/deploy.sh
